### ISSUE TITLE
Improve UndoCommand code quality

### ISSUE THREAD

**Issue by evilmtv** [CS2103AUG2016-T17-C3/main#135]
![image](https://cloud.githubusercontent.com/assets/19277738/20034345/61dfb956-a3f5-11e6-94a1-ae22d029f8d9.png)

**Comment by evilmtv** [comment]
https://www.codacy.com/app/evilmtv/main/dashboard
click on `error prone`

**Comment by ghurabah93** [comment]
Thanks!
