### ISSUE TITLE
Don't show details in UI if null

### ISSUE THREAD

**Issue by evilmtv** [CS2103AUG2016-T17-C3/main#41]
![image](https://cloud.githubusercontent.com/assets/19277738/19604215/df2c5196-97e6-11e6-8ae4-3c4ee724bd91.png)

**Comment by nyannnnnnn** [comment]
I have done this in a tricky tip

**Comment by nyannnnnnn** [comment]
actually, still no solved

**Comment by ghurabah93** [comment]
I'll try to do this !
