### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by ysqty** [CS2103AUG2016-T17-C3/main#54]
# Developer Guide
- Update all your component diagrams, i.e. `UI`, `Logic`, `Storage`, `Model`, etc
- Provide more sequence diagrams for different operations, i.e. `add`, `edit`, `delete`, `find`, etc
- Update and provide more use cases for the different operations
- If possible, try to come up with a few more Non-functional requirements
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
    Similarly, you can explain other interesting design decisions you made.
    May be it's time to get rid of unused code and bring up your coverage level?
# User Guide
- Numbering format issue here

<img width="734" alt="issue1" src="https://cloud.githubusercontent.com/assets/2897395/19654236/12b96f02-9a4a-11e6-98ba-3ec89ac4d89f.PNG">
- The example given for `add` command is incorrect. There shouldn't be a comma after the project title, right? :P

<img width="540" alt="issue2" src="https://cloud.githubusercontent.com/assets/2897395/19654240/17bf8626-9a4a-11e6-8299-a74c778ae0cd.PNG">
- Think about the UX for changing working directory, ie. `directory` Can it be made such that a restart is not needed?

<img width="626" alt="featureux" src="https://cloud.githubusercontent.com/assets/2897395/19654243/1a707830-9a4a-11e6-9a77-80e8aa21bf43.PNG">
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
-  If you are interested in making the product actually usable, there are more things that can be done, some even without much effort. e.g. giving shorter aliases for commands. Also, try different symbols and find the one that doesn't slow down the typing speed.
- Think how to optimize the UI further. Dogfood it as much as possible on a daily basis. When you add/edit/delete, does it give visual cues to confirm what happened was exactly what user intended? Hint hint: Recall what I mentioned during the tutorial about the status box that shows information after every command execution
# ReadMe
- Update it with the relevant Travis CI status badges

**Comment by evilmtv** [comment]
Thank you for the input! We will work on it accordingly

**Comment by ghurabah93** [comment]
I dun quite understand what u mean by this: 

"Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way. Similarly, you can explain other interesting design decisions you made. May be it's time to get rid of unused code and bring up your coverage level?" 

Btw i think we'll be using ONLY undo as of now. So how do i explain how i do undo command?

**Comment by evilmtv** [comment]
Most issues are addressed, unresolved issues from feedback are viewable in issue tracker.
